# Generated by Django 4.2.3 on 2025-04-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send private email', 'can send private email to user by the button')]},
        ),
    ]
